openapi: 3.0.1
info:
  title: Database
  version: 0.1.0
servers:
- url: "{server}:{port}/database"
  variables:
    server:
      default: http://localhost
    port:
      default: HTTP_PORT
paths:
  /email/{staffId}:
    get:
      summary: Description.
      operationId: getEmailStaffid
      parameters:
      - name: staffId
        in: path
        description: parameter description
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items: {}
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /newdata:
    post:
      summary: Description.
      operationId: postNewdata
      requestBody:
        content:
          '*/*':
            schema:
              description: Any type of entity body
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /emaillist:
    get:
      summary: Description.
      operationId: getEmaillist
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items: {}
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /usernamelist:
    get:
      summary: Description.
      operationId: getUsernamelist
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items: {}
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /email:
    delete:
      summary: Description.
      operationId: deleteEmail
      parameters:
      - name: staffid
        in: query
        description: parameter description
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items: {}
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
