openapi: 3.0.1
info:
  title: Find
  version: 0.1.0
servers:
- url: "{server}:{port}/find"
  variables:
    server:
      default: http://localhost
    port:
      default: HTTP_PORT
paths:
  /email:
    get:
      summary: Description.
      operationId: getEmail
      parameters:
      - name: username
        in: query
        description: parameter description
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items: {}
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
