[package]
org = "gunasegarran"
name = "BallerinaApp"
version = "0.1.0"
distribution = "2201.8.3"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.17"

[[platform.java17.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"